client_width: 1024
client_height: 786


number_of_mining_lasers: 2
number_of_drones: 2


check_for_players: True

check_for_player_frigates_and_destroyers: True
check_for_player_cruisers_and_battlecruisers: True
check_for_player_battleships: True

check_for_player_industrials: True
check_for_player_mining_barges: True
check_for_player_capital_industrials_and_freighters: True

check_for_player_rookie_ships: True
check_for_player_capsules: True


check_for_rats: False

check_for_rat_frigates_and_destroyers: True
check_for_rat_cruisers_and_battlecruisers: True
check_for_rat_battleships: True


check_for_ECM_jamming: True